postgres_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: 
      password: 
      port: 
      dbname: postgres
      schema: data_warehouse
      threads: 1
